# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/pinout.xdc

# Block Designs: bd/base_mb/base_mb.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb || ORIG_REF_NAME==base_mb} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_microblaze_0_0/base_mb_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_microblaze_0_0 || ORIG_REF_NAME==base_mb_microblaze_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_mdm_1_0/base_mb_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_mdm_1_0 || ORIG_REF_NAME==base_mb_mdm_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_clk_wiz_1_0/base_mb_clk_wiz_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_1_0 || ORIG_REF_NAME==base_mb_clk_wiz_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_0/base_mb_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_uartlite_0_0/base_mb_axi_uartlite_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_0_0 || ORIG_REF_NAME==base_mb_axi_uartlite_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_microblaze_0_axi_periph_0/base_mb_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_microblaze_0_axi_periph_0 || ORIG_REF_NAME==base_mb_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_dlmb_v10_0/base_mb_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_dlmb_v10_0 || ORIG_REF_NAME==base_mb_dlmb_v10_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ilmb_v10_0/base_mb_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ilmb_v10_0 || ORIG_REF_NAME==base_mb_ilmb_v10_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_dlmb_bram_if_cntlr_0/base_mb_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==base_mb_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ilmb_bram_if_cntlr_0/base_mb_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==base_mb_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_lmb_bram_0/base_mb_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_lmb_bram_0 || ORIG_REF_NAME==base_mb_lmb_bram_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/base_mb_axi_ethernet_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_ethernet_0_0 || ORIG_REF_NAME==base_mb_axi_ethernet_0_0} -quiet] -quiet

# Block Designs: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/bd_0b46.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46 || ORIG_REF_NAME==bd_0b46} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0b46_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_eth_buf_0 || ORIG_REF_NAME==bd_0b46_eth_buf_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_1/bd_0b46_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_mac_0 || ORIG_REF_NAME==bd_0b46_mac_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_2/bd_0b46_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_pcs_pma_0 || ORIG_REF_NAME==bd_0b46_pcs_pma_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_3/bd_0b46_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_0b46_xlconstant_phyadd_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_4/bd_0b46_xlconstant_config_vec_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_0b46_xlconstant_config_vec_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_5/bd_0b46_xlconstant_config_val_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_xlconstant_config_val_0 || ORIG_REF_NAME==bd_0b46_xlconstant_config_val_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_6/bd_0b46_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_c_shift_ram_0_0 || ORIG_REF_NAME==bd_0b46_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_7/bd_0b46_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_c_counter_binary_0_0 || ORIG_REF_NAME==bd_0b46_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_8/bd_0b46_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_xlconstant_0_0 || ORIG_REF_NAME==bd_0b46_xlconstant_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_9/bd_0b46_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_0b46_util_vector_logic_0_0 || ORIG_REF_NAME==bd_0b46_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_0_fifo_0/base_mb_axi_ethernet_0_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_ethernet_0_fifo_0 || ORIG_REF_NAME==base_mb_axi_ethernet_0_fifo_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_intc_0_0/base_mb_axi_intc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_intc_0_0 || ORIG_REF_NAME==base_mb_axi_intc_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_timer_0_0/base_mb_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_timer_0_0 || ORIG_REF_NAME==base_mb_axi_timer_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_0_0/base_mb_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_0_0 || ORIG_REF_NAME==base_mb_xlconstant_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_iic_0_0/base_mb_axi_iic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_iic_0_0 || ORIG_REF_NAME==base_mb_axi_iic_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_1_0/base_mb_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_1_0 || ORIG_REF_NAME==base_mb_xlconstant_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconcat_0_0/base_mb_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconcat_0_0 || ORIG_REF_NAME==base_mb_xlconcat_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_quad_spi_0_0/base_mb_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==base_mb_axi_quad_spi_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_maroc_slow_control_0_0/base_mb_maroc_slow_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_maroc_slow_control_0_0 || ORIG_REF_NAME==base_mb_maroc_slow_control_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_maroc_slow_control_0_0/src/fifo_32by128/fifo_32by128.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_32by128 || ORIG_REF_NAME==fifo_32by128} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_maroc_dc_0_0/base_mb_maroc_dc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_maroc_dc_0_0 || ORIG_REF_NAME==base_mb_maroc_dc_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_maroc_dc_0_0/src/FIFO_32by512/FIFO_32by512.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_32by512 || ORIG_REF_NAME==FIFO_32by512} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_maroc_dc_0_0/src/FIFO_64_to_32/FIFO_64_to_32.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==FIFO_64_to_32 || ORIG_REF_NAME==FIFO_64_to_32} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_2_0/base_mb_xlconstant_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_2_0 || ORIG_REF_NAME==base_mb_xlconstant_2_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_gpio_0_0/base_mb_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_0 || ORIG_REF_NAME==base_mb_axi_gpio_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_0_0/base_mb_xlslice_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_0_0 || ORIG_REF_NAME==base_mb_xlslice_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_1_0/base_mb_rst_clk_wiz_1_100M_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xadc_wiz_0_0/base_mb_xadc_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xadc_wiz_0_0 || ORIG_REF_NAME==base_mb_xadc_wiz_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_stim_gen_0_0/base_mb_stim_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_stim_gen_0_0 || ORIG_REF_NAME==base_mb_stim_gen_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_0_1/base_mb_xlslice_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_0_1 || ORIG_REF_NAME==base_mb_xlslice_0_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_1_0/base_mb_xlslice_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_1_0 || ORIG_REF_NAME==base_mb_xlslice_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_0_2/base_mb_xlslice_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_0_2 || ORIG_REF_NAME==base_mb_xlslice_0_2} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_2_1/base_mb_xlconstant_2_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_2_1 || ORIG_REF_NAME==base_mb_xlconstant_2_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_fifo_mm_s_0_0/base_mb_axi_fifo_mm_s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_fifo_mm_s_0_0 || ORIG_REF_NAME==base_mb_axi_fifo_mm_s_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_in_buf_ds_4bit_0_0/base_mb_in_buf_ds_4bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_in_buf_ds_4bit_0_0 || ORIG_REF_NAME==base_mb_in_buf_ds_4bit_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_in_buf_ds_1bit_0_0/base_mb_in_buf_ds_1bit_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_in_buf_ds_1bit_0_0 || ORIG_REF_NAME==base_mb_in_buf_ds_1bit_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_fifo_mm_s_PH_0/base_mb_axi_fifo_mm_s_PH_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_fifo_mm_s_PH_0 || ORIG_REF_NAME==base_mb_axi_fifo_mm_s_PH_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_clk_wiz_0_0/base_mb_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_0_0 || ORIG_REF_NAME==base_mb_clk_wiz_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_elapsed_time_gen_0_0/base_mb_elapsed_time_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_elapsed_time_gen_0_0 || ORIG_REF_NAME==base_mb_elapsed_time_gen_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_in_buf_ds_1bit_0_1/base_mb_in_buf_ds_1bit_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_in_buf_ds_1bit_0_1 || ORIG_REF_NAME==base_mb_in_buf_ds_1bit_0_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_timebase_wdt_0_0/base_mb_axi_timebase_wdt_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_timebase_wdt_0_0 || ORIG_REF_NAME==base_mb_axi_timebase_wdt_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconcat_1_0/base_mb_xlconcat_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconcat_1_0 || ORIG_REF_NAME==base_mb_xlconcat_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_1_1/base_mb_xlslice_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_1_1 || ORIG_REF_NAME==base_mb_xlslice_1_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xbar_0/base_mb_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xbar_0 || ORIG_REF_NAME==base_mb_xbar_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_wrc_board_quabo_Light_0_2/base_mb_wrc_board_quabo_Light_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_wrc_board_quabo_Light_0_2 || ORIG_REF_NAME==base_mb_wrc_board_quabo_Light_0_2} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_5_0/base_mb_xlslice_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_5_0 || ORIG_REF_NAME==base_mb_xlslice_5_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_SPI_MUX_1_0/base_mb_SPI_MUX_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_SPI_MUX_1_0 || ORIG_REF_NAME==base_mb_SPI_MUX_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_SPI_access_0_0/base_mb_SPI_access_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_SPI_access_0_0 || ORIG_REF_NAME==base_mb_SPI_access_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_6_0/base_mb_xlslice_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_6_0 || ORIG_REF_NAME==base_mb_xlslice_6_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_3_0/base_mb_xlconstant_3_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_3_0 || ORIG_REF_NAME==base_mb_xlconstant_3_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_5_0/base_mb_xlconstant_5_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_5_0 || ORIG_REF_NAME==base_mb_xlconstant_5_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconstant_6_0/base_mb_xlconstant_6_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconstant_6_0 || ORIG_REF_NAME==base_mb_xlconstant_6_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_flash_control_0_0/base_mb_flash_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_flash_control_0_0 || ORIG_REF_NAME==base_mb_flash_control_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_stepper_control_0_0/base_mb_stepper_control_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_stepper_control_0_0 || ORIG_REF_NAME==base_mb_stepper_control_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_2_0/base_mb_xlslice_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_2_0 || ORIG_REF_NAME==base_mb_xlslice_2_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_16_18_0/base_mb_Bit_16_18_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_16_18_0 || ORIG_REF_NAME==base_mb_Bit_16_18_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_19_23_0/base_mb_Bit_19_23_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_19_23_0 || ORIG_REF_NAME==base_mb_Bit_19_23_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_gpio_0_1/base_mb_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_1 || ORIG_REF_NAME==base_mb_axi_gpio_0_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_16_18_1/base_mb_Bit_16_18_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_16_18_1 || ORIG_REF_NAME==base_mb_Bit_16_18_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_0_15_0/base_mb_Bit_0_15_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_0_15_0 || ORIG_REF_NAME==base_mb_Bit_0_15_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlconcat_2_0/base_mb_xlconcat_2_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlconcat_2_0 || ORIG_REF_NAME==base_mb_xlconcat_2_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_16_16_1/base_mb_Bit_16_16_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_16_16_1 || ORIG_REF_NAME==base_mb_Bit_16_16_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_21_21_0/base_mb_Bit_21_21_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_21_21_0 || ORIG_REF_NAME==base_mb_Bit_21_21_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_Bit_22_22_0/base_mb_Bit_22_22_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_Bit_22_22_0 || ORIG_REF_NAME==base_mb_Bit_22_22_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_PPS_IO_0_0/base_mb_PPS_IO_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_PPS_IO_0_0 || ORIG_REF_NAME==base_mb_PPS_IO_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xlslice_0_3/base_mb_xlslice_0_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xlslice_0_3 || ORIG_REF_NAME==base_mb_xlslice_0_3} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_0/base_mb_ETH_CORE_CTRL_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ETH_CORE_CTRL_0_0 || ORIG_REF_NAME==base_mb_ETH_CORE_CTRL_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_0/ip/fifo_generator_0/fifo_generator_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_AXI_Stream_Switch_0_0/base_mb_AXI_Stream_Switch_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_AXI_Stream_Switch_0_0 || ORIG_REF_NAME==base_mb_AXI_Stream_Switch_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_AXI_Stream_Switch_0_0/ip/axis_switch_0/axis_switch_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==axis_switch_0 || ORIG_REF_NAME==axis_switch_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_FIFO_for_AXIS_0_0/base_mb_FIFO_for_AXIS_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_FIFO_for_AXIS_0_0 || ORIG_REF_NAME==base_mb_FIFO_for_AXIS_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_FIFO_for_AXIS_0_0/ip/fifo_generator_1/fifo_generator_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/base_mb_axi_ethernet_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_ethernet_1_0 || ORIG_REF_NAME==base_mb_axi_ethernet_1_0} -quiet] -quiet

# Block Designs: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/bd_cb17.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17 || ORIG_REF_NAME==bd_cb17} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_0/bd_cb17_eth_buf_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_eth_buf_0 || ORIG_REF_NAME==bd_cb17_eth_buf_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_1/bd_cb17_mac_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_mac_0 || ORIG_REF_NAME==bd_cb17_mac_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_2/bd_cb17_pcs_pma_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_pcs_pma_0 || ORIG_REF_NAME==bd_cb17_pcs_pma_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_3/bd_cb17_xlconstant_phyadd_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_xlconstant_phyadd_0 || ORIG_REF_NAME==bd_cb17_xlconstant_phyadd_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_4/bd_cb17_xlconstant_config_vec_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_xlconstant_config_vec_0 || ORIG_REF_NAME==bd_cb17_xlconstant_config_vec_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_5/bd_cb17_xlconstant_config_val_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_xlconstant_config_val_0 || ORIG_REF_NAME==bd_cb17_xlconstant_config_val_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_6/bd_cb17_c_shift_ram_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_c_shift_ram_0_0 || ORIG_REF_NAME==bd_cb17_c_shift_ram_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_7/bd_cb17_c_counter_binary_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_c_counter_binary_0_0 || ORIG_REF_NAME==bd_cb17_c_counter_binary_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_8/bd_cb17_xlconstant_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_xlconstant_0_0 || ORIG_REF_NAME==bd_cb17_xlconstant_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_9/bd_cb17_util_vector_logic_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==bd_cb17_util_vector_logic_0_0 || ORIG_REF_NAME==bd_cb17_util_vector_logic_0_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_2/base_mb_ETH_CORE_CTRL_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_ETH_CORE_CTRL_0_2 || ORIG_REF_NAME==base_mb_ETH_CORE_CTRL_0_2} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_2/ip/fifo_generator_0/fifo_generator_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_uartlite_1_0/base_mb_axi_uartlite_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_1_0 || ORIG_REF_NAME==base_mb_axi_uartlite_1_0} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_xbar_2/base_mb_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_xbar_2 || ORIG_REF_NAME==base_mb_xbar_2} -quiet] -quiet

# IP: bd/base_mb/ip/base_mb_axi_interconnect_0_1/base_mb_axi_interconnect_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==base_mb_axi_interconnect_0_1 || ORIG_REF_NAME==base_mb_axi_interconnect_0_1} -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_microblaze_0_0/base_mb_microblaze_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_microblaze_0_0 || ORIG_REF_NAME==base_mb_microblaze_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_microblaze_0_0/base_mb_microblaze_0_0_ooc_debug.xdc

# XDC: bd/base_mb/ip/base_mb_mdm_1_0/base_mb_mdm_1_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_mdm_1_0 || ORIG_REF_NAME==base_mb_mdm_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_mdm_1_0/base_mb_mdm_1_0_ooc_trace.xdc

# XDC: bd/base_mb/ip/base_mb_clk_wiz_1_0/base_mb_clk_wiz_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_1_0 || ORIG_REF_NAME==base_mb_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_clk_wiz_1_0/base_mb_clk_wiz_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_1_0 || ORIG_REF_NAME==base_mb_clk_wiz_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_clk_wiz_1_0/base_mb_clk_wiz_1_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_0/base_mb_rst_clk_wiz_1_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_0/base_mb_rst_clk_wiz_1_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_0_0/base_mb_axi_uartlite_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_0_0 || ORIG_REF_NAME==base_mb_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_0_0/base_mb_axi_uartlite_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_0_0/base_mb_axi_uartlite_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_0_0 || ORIG_REF_NAME==base_mb_axi_uartlite_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_dlmb_v10_0/base_mb_dlmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_dlmb_v10_0 || ORIG_REF_NAME==base_mb_dlmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_ilmb_v10_0/base_mb_ilmb_v10_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_ilmb_v10_0 || ORIG_REF_NAME==base_mb_ilmb_v10_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_lmb_bram_0/base_mb_lmb_bram_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/base_mb_axi_ethernet_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_ethernet_0_0 || ORIG_REF_NAME==base_mb_axi_ethernet_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/synth/base_mb_axi_ethernet_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_0/bd_0b46_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_eth_buf_0 || ORIG_REF_NAME==bd_0b46_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_0/synth/bd_0b46_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_eth_buf_0 || ORIG_REF_NAME==bd_0b46_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0b46_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_mac_0 || ORIG_REF_NAME==bd_0b46_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0b46_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_mac_0 || ORIG_REF_NAME==bd_0b46_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0b46_mac_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_1/synth/bd_0b46_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_mac_0 || ORIG_REF_NAME==bd_0b46_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_2/bd_0b46_pcs_pma_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_pcs_pma_0 || ORIG_REF_NAME==bd_0b46_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_2/synth/bd_0b46_pcs_pma_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_0b46_pcs_pma_0 || ORIG_REF_NAME==bd_0b46_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/ip/ip_2/synth/bd_0b46_pcs_pma_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_0_0/bd_0/bd_0b46_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_intc_0_0/base_mb_axi_intc_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_intc_0_0 || ORIG_REF_NAME==base_mb_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_intc_0_0/base_mb_axi_intc_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_intc_0_0 || ORIG_REF_NAME==base_mb_axi_intc_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_intc_0_0/base_mb_axi_intc_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_timer_0_0/base_mb_axi_timer_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_timer_0_0 || ORIG_REF_NAME==base_mb_axi_timer_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_timer_0_0/base_mb_axi_timer_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_iic_0_0/base_mb_axi_iic_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_iic_0_0 || ORIG_REF_NAME==base_mb_axi_iic_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_iic_0_0/base_mb_axi_iic_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_quad_spi_0_0/base_mb_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==base_mb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_quad_spi_0_0/base_mb_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==base_mb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_quad_spi_0_0/base_mb_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_quad_spi_0_0/base_mb_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_quad_spi_0_0 || ORIG_REF_NAME==base_mb_axi_quad_spi_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_maroc_slow_control_0_0/src/fifo_32by128/fifo_32by128.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_32by128 || ORIG_REF_NAME==fifo_32by128} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_maroc_dc_0_0/src/FIFO_32by512/FIFO_32by512.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_32by512 || ORIG_REF_NAME==FIFO_32by512} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_maroc_dc_0_0/src/FIFO_64_to_32/FIFO_64_to_32.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_64_to_32 || ORIG_REF_NAME==FIFO_64_to_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_maroc_dc_0_0/src/FIFO_64_to_32/FIFO_64_to_32_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==FIFO_64_to_32 || ORIG_REF_NAME==FIFO_64_to_32} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_0/base_mb_axi_gpio_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_0 || ORIG_REF_NAME==base_mb_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_0/base_mb_axi_gpio_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_0/base_mb_axi_gpio_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_0 || ORIG_REF_NAME==base_mb_axi_gpio_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_1_0/base_mb_rst_clk_wiz_1_100M_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_rst_clk_wiz_1_100M_1_0/base_mb_rst_clk_wiz_1_100M_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0 || ORIG_REF_NAME==base_mb_rst_clk_wiz_1_100M_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_xadc_wiz_0_0/base_mb_xadc_wiz_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_xadc_wiz_0_0/base_mb_xadc_wiz_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_xadc_wiz_0_0 || ORIG_REF_NAME==base_mb_xadc_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_clk_wiz_0_0/base_mb_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_0_0 || ORIG_REF_NAME==base_mb_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_clk_wiz_0_0/base_mb_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_clk_wiz_0_0 || ORIG_REF_NAME==base_mb_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_clk_wiz_0_0/base_mb_clk_wiz_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_timebase_wdt_0_0/base_mb_axi_timebase_wdt_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_timebase_wdt_0_0 || ORIG_REF_NAME==base_mb_axi_timebase_wdt_0_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_timebase_wdt_0_0/base_mb_axi_timebase_wdt_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_1/base_mb_axi_gpio_0_1_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_1 || ORIG_REF_NAME==base_mb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_1/base_mb_axi_gpio_0_1_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_gpio_0_1/base_mb_axi_gpio_0_1.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_gpio_0_1 || ORIG_REF_NAME==base_mb_axi_gpio_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_0/ip/fifo_generator_0/fifo_generator_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_0/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_AXI_Stream_Switch_0_0/ip/axis_switch_0/axis_switch_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_FIFO_for_AXIS_0_0/ip/fifo_generator_1/fifo_generator_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_FIFO_for_AXIS_0_0/ip/fifo_generator_1/fifo_generator_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_1 || ORIG_REF_NAME==fifo_generator_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/base_mb_axi_ethernet_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_ethernet_1_0 || ORIG_REF_NAME==base_mb_axi_ethernet_1_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/synth/base_mb_axi_ethernet_1_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_0/bd_cb17_eth_buf_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_eth_buf_0 || ORIG_REF_NAME==bd_cb17_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_0/synth/bd_cb17_eth_buf_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_eth_buf_0 || ORIG_REF_NAME==bd_cb17_eth_buf_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_0/bd_cb17_eth_buf_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_cb17_mac_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_mac_0 || ORIG_REF_NAME==bd_cb17_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_cb17_mac_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_mac_0 || ORIG_REF_NAME==bd_cb17_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_cb17_mac_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_1/synth/bd_cb17_mac_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_mac_0 || ORIG_REF_NAME==bd_cb17_mac_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_2/bd_cb17_pcs_pma_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_pcs_pma_0 || ORIG_REF_NAME==bd_cb17_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_2/synth/bd_cb17_pcs_pma_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==bd_cb17_pcs_pma_0 || ORIG_REF_NAME==bd_cb17_pcs_pma_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_2/synth/bd_cb17_pcs_pma_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_6/bd_cb17_c_shift_ram_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/ip/ip_7/bd_cb17_c_counter_binary_0_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_ethernet_1_0/bd_0/bd_cb17_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_2/ip/fifo_generator_0/fifo_generator_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_ETH_CORE_CTRL_0_2/ip/fifo_generator_0/fifo_generator_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==fifo_generator_0 || ORIG_REF_NAME==fifo_generator_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_1_0/base_mb_axi_uartlite_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_1_0 || ORIG_REF_NAME==base_mb_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_1_0/base_mb_axi_uartlite_1_0_ooc.xdc

# XDC: bd/base_mb/ip/base_mb_axi_uartlite_1_0/base_mb_axi_uartlite_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==base_mb_axi_uartlite_1_0 || ORIG_REF_NAME==base_mb_axi_uartlite_1_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/base_mb/ip/base_mb_xbar_2/base_mb_xbar_2_ooc.xdc

# XDC: bd/base_mb/base_mb_ooc.xdc
