webtalk_init -webtalk_dir /media/wei/DATA/LW/quabo_V008/quabo3_Viv20183.sdk/WS3_WR/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2019-10-30 22:03:03" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.3" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211461594_0_0_907" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "75mtit8scjmmbqirk7og1lqdub" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.3_127" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "127" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.3 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3783.367 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "25.127 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1572498084000" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key isZynq -value "false" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key Processors -value "1" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.3_AR71948" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key Arch -value "kintex7" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key Device -value "7k160t" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1572498084000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1572498182259"
webtalk_transmit -clientid 696965640 -regid "211461594_0_0_907" -xml /media/wei/DATA/LW/quabo_V008/quabo3_Viv20183.sdk/WS3_WR/webtalk/usage_statistics_ext_sdk.xml -html /media/wei/DATA/LW/quabo_V008/quabo3_Viv20183.sdk/WS3_WR/webtalk/usage_statistics_ext_sdk.html -wdm /media/wei/DATA/LW/quabo_V008/quabo3_Viv20183.sdk/WS3_WR/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
